### ISSUE TITLE
Unable to find instructions for build

### ISSUE THREAD

**Issue by schwabts** [aquaULB/solving_pde_mooc#23]
* Usually we call `jupyter-book build folder` if `_toc.yml` and `_config.yml` are located in folder `folder`.
* In non-standard setups users are extremely grateful for instructions how to build a project.

```
$ jupyter-book build .
Running Jupyter-Book v0.13.0
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-book.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_book\cli\main.py", line 236, in build
    _error(
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_book\utils.py", line 48, in _error
    raise kind(box)
RuntimeError:
===============================================================================

Couldn't find a Table of Contents file. To auto-generate one, run:

        jupyter-book toc from-project .

===============================================================================

```

**Comment by schwabts** [comment]
go to [instructions](https://github.com/aquaULB/book_solving_pde_mooc)
